# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas Audinet de Pieuchon
url:              http://nicaudinet.github.io
baseurl:          https://nicaudinet.github.io/
# baseurl:          /

author:
  name:           'Nicolas Audinet de Pieuchon'
  url:            https://www.linkedin.com/in/nicolas-audinet/

plugins: []
