# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas Audinet de Pieuchon
# tagline:          'A Jekyll theme'
description:      'Causality, NLP, Haskell'
url:              http://nicaudinet.github.io
baseurl:          /

author:
  name:           'Nicolas Audinet de Pieuchon'
  url:            https://www.linkedin.com/in/nicolas-audinet/

plugins: [jekyll-paginate]

paginate:         10
paginate_path: "/_posts/page:num"
